services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - SRC_DIR=${SRC_DIR}
        - DEP_DIR=${DEP_DIR}
    # image: ${PREFIX}/env
    # ports:
    #   - "8081:8081"
    # stdin_open: true
    # tty: true
    user: root
    volumes: 
      - ${ROOTDIR}:/home/user/repo
      # - ${ROOTDIR}/exec:/bin
    # depends_on: 
    # - postgres

  postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=${POSTGRESUSER}
        - POSTGRES_PASSWORD=${POSTGRESPASSWORD}
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
      # volumes: 
      #  - ${ROOTDIR}:/var/lib/postgresql/data
      #  - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql